version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - django-app
      - flask-app

  django-app:
    build: ./django_app/excel_web_app
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=excel_web_app.settings
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles

  flask-app:
    build: ./flask_app
    expose:
      - "5000"
    command: gunicorn --bind 0.0.0.0:5000 app:app

volumes:
  static_volume:
